### ISSUE TITLE
Using with vanilla Framer.js does not work

### ISSUE THREAD

**Issue by bstaats** [facebook/shortcuts-for-framer#23]
Line 573 of build/shortcuts.js breaks since `exports` is not part of the vanilla environment.

Thanks!

**Comment by cemre** [comment]
Thanks, this sounds correct. I guess we'll need to ship two different builds of this.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by cemre** [comment]
It seems like the vanilla environment isn't being used a ton anymore so I took out the reference.
