### ISSUE TITLE
shortcuts.initialize(myLayers) Error

### ISSUE THREAD

**Issue by ben02influx** [facebook/shortcuts-for-framer#24]
When I initialize with my sketch layer, I get an error from Framer saying "ReferenceError: Can't find variable: shortcuts".

Other commands like layer.animateTo work fine.

**Comment by cemre** [comment]
Can you ZIP up your project and send a link?

**Comment by cemre** [comment]
I should probably deprecate it since Framer has a builtin utility for this now.
